import Head from "next/head";
import React from "react";

export const Header = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-10">
        <h1>Header部分：SampleTest</h1>
      </div>
    </>
  );
};
